"""INFRACORE — LateChunkingEmbedder

Embedding chunks of documents by token offset pooling on full document hidden states.
Async-first, lazy loading, Pydantic configuration, and Prometheus metrics.
"""

import time
from typing import List, Optional

import numpy as np
from prometheus_client import Counter, Histogram
from pydantic import Field, ConfigDict

try:
    import torch
    from transformers import AutoModel, AutoTokenizer
except ImportError:
    torch = None
    AutoModel = None
    AutoTokenizer = None

from src.infracore.embedding.base import BaseEmbedder, EmbedConfig


class LateChunkingConfig(EmbedConfig):
    """Configuration for LateChunkingEmbedder."""

    model_config = ConfigDict(frozen=True)

    model_name: str = Field(default="BAAI/bge-m3", description="HuggingFace model ID or path")
    device: str = Field(default="auto", description="Device: 'auto', 'cuda', 'mps', or 'cpu'")
    max_doc_tokens: int = Field(default=8192, description="Max tokens for full document sequence")
    pooling_strategy: str = Field(default="mean", description="Token pooling strategy: 'mean'")
    batch_size: int = Field(default=8, description="Batch size for documents processing")


# Prometheus metrics
late_chunking_embed_total = Counter(
    "late_chunking_embed_total",
    "Total chunk embeddings generated by late chunking",
    ["model_name"],
)

late_chunking_embed_latency_seconds = Histogram(
    "late_chunking_embed_latency_seconds",
    "Late chunking embed operation latency in seconds",
    ["model_name"],
)


class LateChunkingEmbedder(BaseEmbedder):
    """Late chunking embedder to preserve global document context.

    Loads transformers model lazily on first embedding execution.
    """

    def __init__(self, config: LateChunkingConfig):
        super().__init__(config)
        self.config = config
        self.model = None
        self.tokenizer = None
        self.device = self._detect_device()

    def _detect_device(self) -> str:
        """Detect best available device if configured as 'auto'."""
        if self.config.device != "auto":
            return self.config.device
        if torch is not None:
            if torch.cuda.is_available():
                return "cuda"
            elif getattr(torch.backends, "mps", None) is not None and torch.backends.mps.is_available():
                return "mps"
        return "cpu"

    def _load_model(self) -> None:
        """Lazy load tokenizer and model."""
        if self.model is not None:
            return

        if torch is None or AutoModel is None or AutoTokenizer is None:
            raise ImportError(
                "PyTorch and transformers libraries are required for LateChunkingEmbedder. "
                "Please install them via: pip install torch transformers"
            )

        self.tokenizer = AutoTokenizer.from_pretrained(self.config.model_name)
        self.model = AutoModel.from_pretrained(self.config.model_name)
        self.model.to(self.device)
        self.model.eval()

        # Deduce dimensions from model config
        self.embedding_dim = getattr(self.model.config, "hidden_size", 1024)

    async def embed(self, chunks: List[str], doc_text: str = "") -> np.ndarray:
        """Embed a set of chunks with global document context.

        Args:
            chunks: List of text chunks.
            doc_text: Full document text. If not provided, standard independent embedding is used.

        Returns:
            np.ndarray of shape (len(chunks), embedding_dim)
        """
        if not chunks:
            return np.empty((0, self.embedding_dim or 1024), dtype=np.float32)

        # Fallback to independent chunk embedding if no full doc_text is supplied
        if not doc_text:
            return await self._embed_independent(chunks)

        self._load_model()
        start_time = time.perf_counter()

        # Tokenize the document and request character offset mapping
        inputs = self.tokenizer(
            doc_text,
            return_tensors="pt",
            return_offsets_mapping=True,
            max_length=self.config.max_doc_tokens,
            truncation=True,
        )

        offset_mapping = inputs.pop("offset_mapping")[0].tolist()
        inputs = {k: v.to(self.device) for k, v in inputs.items()}

        with torch.no_grad():
            outputs = self.model(**inputs)
            # Retrieve token hidden states (shape: sequence_length, hidden_dim)
            token_embeddings = outputs.last_hidden_state[0].cpu().numpy()

        # Find character offset ranges of each chunk in the full doc_text
        char_spans = []
        current_idx = 0
        for chunk in chunks:
            idx = doc_text.find(chunk, current_idx)
            if idx != -1:
                start = idx
                end = idx + len(chunk)
                current_idx = end
            else:
                idx = doc_text.find(chunk)
                if idx != -1:
                    start = idx
                    end = idx + len(chunk)
                else:
                    start = current_idx
                    end = current_idx
            char_spans.append((start, end))

        chunk_vectors = []
        for start_char, end_char in char_spans:
            # Map character spans to corresponding token indices
            token_indices = []
            for token_idx, (token_start, token_end) in enumerate(offset_mapping):
                if token_start == 0 and token_end == 0:
                    continue  # skip special tokens
                if start_char <= token_start < end_char:
                    token_indices.append(token_idx)

            if not token_indices:
                # Find closest token start character fallback
                closest_idx = 0
                min_dist = float("inf")
                for token_idx, (token_start, token_end) in enumerate(offset_mapping):
                    if token_start == 0 and token_end == 0:
                        continue
                    dist = abs(token_start - start_char)
                    if dist < min_dist:
                        min_dist = dist
                        closest_idx = token_idx
                token_indices = [closest_idx]

            # Pool hidden states over token indices span
            chunk_vector = np.mean(token_embeddings[token_indices], axis=0)
            chunk_vectors.append(chunk_vector)

        chunk_embeddings = np.vstack(chunk_vectors)

        # L2 Normalize
        norms = np.linalg.norm(chunk_embeddings, axis=1, keepdims=True)
        chunk_embeddings = chunk_embeddings / (norms + 1e-10)

        # Record metrics
        elapsed = time.perf_counter() - start_time
        late_chunking_embed_total.labels(model_name=self.config.model_name).inc(len(chunks))
        late_chunking_embed_latency_seconds.labels(model_name=self.config.model_name).observe(elapsed)

        return chunk_embeddings.astype(np.float32)

    async def _embed_independent(self, texts: List[str]) -> np.ndarray:
        """Fallback method to embed chunks independently."""
        self._load_model()
        all_embeddings = []

        for text in texts:
            inputs = self.tokenizer(
                text,
                return_tensors="pt",
                max_length=self.config.max_length,
                truncation=True,
            )
            inputs = {k: v.to(self.device) for k, v in inputs.items()}
            with torch.no_grad():
                outputs = self.model(**inputs)
                vec = torch.mean(outputs.last_hidden_state[0], dim=0).cpu().numpy()
            
            # Normalize
            norm = np.linalg.norm(vec)
            vec = vec / (norm + 1e-10)
            all_embeddings.append(vec)

        return np.vstack(all_embeddings).astype(np.float32)

    async def embed_single(self, text: str) -> np.ndarray:
        """Embed a single query text using mean pooling on sequence token states."""
        self._load_model()
        inputs = self.tokenizer(
            text,
            return_tensors="pt",
            max_length=self.config.max_length,
            truncation=True,
        )
        inputs = {k: v.to(self.device) for k, v in inputs.items()}

        with torch.no_grad():
            outputs = self.model(**inputs)
            # Mean pool sequence vectors to 1D shape (hidden_dim,)
            query_vector = torch.mean(outputs.last_hidden_state[0], dim=0).cpu().numpy()

        # Normalize
        norm = np.linalg.norm(query_vector)
        query_vector = query_vector / (norm + 1e-10)

        return query_vector.astype(np.float32)
